[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
music_nft = "9ysQaigie6LHeqMEWGMWBYkdXFg4zyHhBnxzmZdMzG7T"

[programs.devnet]
music_nft = "9ysQaigie6LHeqMEWGMWBYkdXFg4zyHhBnxzmZdMzG7T"

[registry]
programs = [
  { name = "music_nft", keypair = "./keys/music_nft-keypair.json" }
]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
